PRNSTR MACRO STR
    MOV AH,09H
    LEA DX,STR
    INT 21H
ENDM

GET_ARR MACRO ARR, NUM
    LOCAL GET_ARR_LOOP
    MOV CX,NUM
    MOV SI,0
    GET_ARR_LOOP:
        MOV AH,01H
        INT 21H
        MOV ARR[SI],AL
        INC SI
        LOOP GET_ARR_LOOP
ENDM